#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# AUTOSTART #
#-----------#
picom --experimental-backend &
xwallpaper --zoom $HOME/.config/herbstluftwm/void5.png
xfce4-power-manager &
polybar -c $HOME/.config/herbstluftwm/polybar_config mainbar-herbst &

# REMOVE ALL EXISTING KEYBINDINGS #
#---------------------------------#
hc keyunbind --all

# KEYBINDINGS #
#-------------#
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

# System controls #
#-----------------#
hc keybind $Mod-Shift-c spawn kitty -T logout -e herbst-logout.sh
hc keybind $Mod-Control-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-kitty}" # 
hc keybind $Mod-Shift-k spawn kitty

# multimedia #
#------------#
hc keybind XF86MonBrightnessUp spawn lux -a 10%
hc keybind XF86MonBrightnessDown spawn lux -s 10%
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -5%
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn playerctl previous
hc keybind $Mod-Control-s spawn playerctl stop

# programs #
# #--------#
hc keybind $Mod-w spawn bgd
hc keybind $Mod-Control-t spawn alacritty -e "$HOME/scripts/changer"
hc keybind $Mod-Control-y spawn ~/.local/scripts/ytsubs.sh
hc keybind $Mod-Control-c spawn $HOME/scripts/herbstchanger
hc keybind $Mod-Control-t spawn $HOME/scripts/changer 
hc keybind $Mod-t spawn alacritty -e ./.local/scripts/schedule.sh
hc keybind $Mod-Shift-w spawn kitty -T windows -e windows.sh

# run launchers #
#---------------#
#hc keybind $Mod-Control-f spawn dmenu_run -p Launch: -fn Hermit:size=10 -l 10 -g 7 -nb '#222222' -sb '#007687' -sf '#222222' -nf '#b8b8b8'
hc keybind $Mod-Shift-r spawn rofi -show drun
hc keybind $Mod-Control-e spawn rofi -show emoji
hc keybind $Mod-Shift-v spawn vmach.sh
hc keybind $Mod-Shift-i spawn kitty -T vsp2 -e vsp2
hc keybind $Mod-Shift-d spawn kitty -T launch.sh -e launch.sh 
hc keybind $Mod-Shift-e spawn kitty -T configs -e edit_configs.sh

# browsers #
#----------#
hc keybind $Mod-Shift-b spawn brave-browser-stable
hc keybind $Mod-Shift-a spawn firefox

# scratchpads #
#-------------#
hc keybind $Mod-Return spawn scratch scratchpad 
hc keybind $Mod-Control-f spawn scratch FM
hc keybind $Mod-q spawn scratch2 qutebrowser 
hc keybind $Mod-Control-Return spawn scratchpad
hc keybind $Mod-m spawn scratch Mail

# focusing client #
#-----------------#s
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients in tiling and floating mode #
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames #
#------------------#
hc keybind $Mod-u       split   bottom  0.6
hc keybind $Mod-o       split   right   0.6

# let the current frame explode into subframes #
#----------------------------------------------#
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients #
#--------------------------------------#
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags #
#------#
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting #
#-----------#
hc keybind $Mod-s spawn new-layout.sh 
hc keybind $Mod-l spawn ./.local/scripts/load-layout.sh
hc keybind $Mod-r remove
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# focus #
#-------#
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# MOUSE #
#-------#
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# THEME #
#-------#
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#007687'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.active.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.color '#b8b8b8'
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings false
hc set smart_frame_surroundings false
hc set mouse_recenter_gap 0

# RULES #
#-------#
hc unrule -F

# MENUS #
#-------#
hc rule title~'launch.sh' floating=on floatplacement=center floating_geometry=600x800
hc rule title~'vsp2' floating=on floatplacement=center floating_geometry=375x1000
hc rule title~'configs' floating=on floatplacement=center floating_geometry=375x600
hc rule title~'windows' floating=on floatplacement=center floating_geometry=600x300
hc rule title~'logout' floating=on floatplacement=center floating_geometry=320x200

# SCRATCHPADS #
#-------------#
hc rule title~'scratchpad' floating=on floatplacement=center floating_geometry=1000x500
hc rule title~'FM' floating=on floatplacement=center floating_geometry=1000x800
hc rule class~'qutebrowser' floating=on floatplacement=center floating_geometry=1800x1000
hc rule title~'Mail' floating=on floatplacement=center floating_geometry=1500x800

hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule float_geometry=250x100
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# UNLOCK #
#--------#
hc unlock


# FIND THE PANEL #
#----------------#
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
hc split vertical 0.6; hc remove
